## 属性

In [1]:
import numpy as np

array = np.array([[1,2,3],[4,5,6]])

print(array)
print(array.ndim) #维度dimenion：几维 2
print(array.shape) #形状：行数和列数 （2，3）
print(array.size) #元素个数 612345678

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


### 创建array

#### arange & linespace

In [8]:
a = np.array([[1,2,3],
             [4,5,6]])
print(a)

a = np.array([[1,2,3],[4,5,6]]) #制定数据的类型 对于array，是dtype，而numpy的常用数据类型有两种：int和float，一般有int16 int32 int64,float同样，数值越大占用内存越大，精度也就越高，但是单位内存下存储的东西也就越少
print(a.dtype) #python3.5及以下版本默认类型为64，python3.6默认为32

a = np.zeros((3,4)) #生成3行4列元素全为0的矩阵
print(a) 

a = np.ones((3,4)) #生成3行4列元素全为1的矩阵，并规定数据类型为float32
print(a)
print(a.dtype)

a = np.empty((3,4)) #生成3行4列且每个元素都接近0的矩阵，据说在python3.6中和zeros是一样的了，未查证
print(a)

#生成等差数列的两个方法：
a = np.arange(10,20,2) #生成连续的数组，从10到20（不包括20），**步长为2**
print(a)
a = np.linspace(10,20,5) #创建线段型数据 从10到20（包括20），**元素个数为5** 
print(a)
a = np.linspace(10,20,num=50, endpoint=True, retstep=False, dtype=None) 
print(a)

a = np.linspace(1,10,20).reshape((5,4)) #改变矩阵的形状，变为5行4列的矩阵
print(a)

[[1 2 3]
 [4 5 6]]
int32
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[10 12 14 16 18]
[10.  12.5 15.  17.5 20. ]
[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789

### array运算

In [3]:
a = np.array([5,2,4,6])
b = np.arange(4) # = np.array([0,1,2,3])

#常规运算 /对每个元素运算
c = a - b #[5,1,2,3]
c = a + b
c = a * b #[0,2,8,18] 对应位置上的元素相乘，并非矩阵乘法
c = a ** 2 #a^2 [25,4,16,36]
c = np.sin(a) #对每个元素求sin
c = 10*np.sin(a)

#逻辑判断，返回一个bool类型的矩阵
print(b<4) #[True,True,True,True]
print(a==2) #[False,True,False,False]
#----------------------------------------------------------------

#上面的运算都是基于一维矩阵/向量/一维数组，现在要对多维矩阵进行运算
a = np.array([[1,1],
              [0,1]]) #2行2列的矩阵
b = np.arange(4).reshape((2,2))

c_dot = np.dot(a,b) #矩阵相乘
c_dot_2 = a.dot(b) #两种方法等价
#-------------------------------------------------------------
a = np.random.random((2,4)) #生成一个所有元素都是0到1的2行4列的随机数矩阵
print(a)
# array([[ 0.94692159,  0.20821798,  0.35339414,  0.2805278 ],
#       [ 0.04836775,  0.04023552,  0.44091941,  0.21665268]])

np.sum(a) #矩阵中所有元素求和
np.min(a) #矩阵中最小值
np.max(a) #矩阵中最大值

#分别计算每一行或者每一列的运算，用到axis=1,0；其中0表示按列，1表示按行
np.sum(a,axis=1)
# sum = [ 1.96877324  2.43558896]
np.min(a,axis=0)
# min = [ 0.23651224  0.41900661  0.36603285  0.46456022]
np.max(a,axis=1)
# max = [ 0.84869417  0.9043845 ]1234567891011121314151617181920212223242526272829303132333435363738394041

[ True  True  True  True]
[False  True False False]
[[0.86139639 0.95621246 0.63821701 0.16048824]
 [0.80629509 0.90847163 0.96819331 0.27234793]]


array([0.95621246, 0.96819331])

In [10]:
A = np.arange(2,14).reshape((3,4))
# array([[ 2, 3, 4, 5]
#        [ 6, 7, 8, 9]
#        [10,11,12,13]])

print(np.argmin(A)) #求矩阵中最小元素的索引，第一个元素记为位置0，最后一个元素对应位置为11   
# 0
print(np.argmax(A))    
# 11

#求平均值 下面四种方法等价：
print(np.mean(A))
print(A.mean())
print(np.median(A))
print(np.average(A))
#7.5

print(np.cumsum(A)) #累加函数，生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和，得到1*12的矩阵
# [2 5 9 14 20 27 35 44 54 6b5 77 90]
print(np.diff(A)) #累差函数，后一项与此项的差作为这一项的元素，得到3*3的矩阵
# [[1 1 1]
#  [1 1 1]
#  [1 1 1]]

print(np.nonzero(A)) #查找哪些位置上的元素非0，结果显示成行与列，一一对应   
#(array([0,0,0,0,1,1,1,1,2,2,2,2]),array([0,1,2,3,0,1,2,3,0,1,2,3]))
A = np.array([[0,1,2],[6,0,8],[9,5,0]])
print(np.nonzero(A))
#(array([0,0,1,1,2,2]),array([1,2,0,2,0,1])) 见下图

A = np.arange(14,2, -1).reshape((3,4)) 
# array([[14, 13, 12, 11],
#       [10,  9,  8,  7],
#       [ 6,  5,  4,  3]])

print(np.sort(A)) #行排序，从小到大   
# array([[11,12,13,14]
#        [ 7, 8, 9,10]
#        [ 3, 4, 5, 6]])

#转置，两种方法等价（A必须是矩阵/一维向量，不能是数组/序列）
print(np.transpose(A))    
print(A.T)
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])
# array([[14,10, 6]
#        [13, 9, 5]
#        [12, 8, 4]
#        [11, 7, 3]])

#clip(array,a,b)函数,其中规定a<b,使矩阵中<a的元素全部变为a，>b的元素全部变为b
print(A)
# array([[14,13,12,11]
#        [10, 9, 8, 7]
#        [ 6, 5, 4, 3]])
print(np.clip(A,5,9))    
# array([[ 9, 9, 9, 9]
#        [ 9, 9, 8, 7]
#        [ 6, 5, 5, 5]])

0
11
7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
(array([0, 0, 1, 1, 2, 2], dtype=int64), array([1, 2, 0, 2, 0, 1], dtype=int64))
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [17]:
print(np.average(A))
B = np.arange(12).reshape((3, 4))
print(B)
B.sort()
print(B)
print(np.average(B))
print(B.argmax())
print(B.argmin())
# print(B[B]) 

8.5
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
5.5
11
0


## numpy索引

In [19]:
A = np.arange(3, 15)
print(A[3])
A = A.reshape((3, 4))
print(A[0])

6
[3 4 5 6]


In [20]:
A = np.arange(3, 15).reshape((3, 4))
print(A)
for row in A:
    print(row)
print("A.T")
print(A.T)
for col in A.T:
    print(col)


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
A.T
[[ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]
 [ 6 10 14]]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


### 迭代输出

In [25]:
A = np.arange(3, 15).reshape((3, 4))
print(A)
print("A.flatten():")
print(A.flatten())
for item in A.flat: #flat为迭代器， 本身是object属性
    print(item, end=" ")
    

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
A.flatten():
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3 4 5 6 7 8 9 10 11 12 13 14 

## numpy array合并

In [ ]:
# np.vstack      
# np.hstack
# np.newaxis
# np.concatenate多矩阵合并

In [26]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
print(np.vstack((A, B)))  #vertiacl

[[1 1 1]
 [2 2 2]]


In [30]:
print(np.hstack((A, B)))

[1 1 1 2 2 2]


In [32]:
print(A[:, np.newaxis])# np.newaxis作用    占位

[[1]
 [1]
 [1]]


In [34]:
A = np.array([1, 1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2, 2])[:, np.newaxis]
print(A, B)
print("np.concatenate(A, B, B, A)")
print(np.concatenate((A, B, B, A), axis=0))
print(np.concatenate((A, B, B, A), axis=1))


[[1]
 [1]
 [1]
 [1]] [[2]
 [2]
 [2]
 [2]]
np.concatenate(A, B, B, A)
[[1]
 [1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [ ]:
a = np.arange(4)
# array([0, 1, 2, 3])

b = a
c = a
d = b

a[0] = 11 #改变a
print(a)
# array([11,  1,  2,  3])

b is a  # True #b c d也会改变
c is a  # True
d is a  # True

d[1:3] = [22, 33]   # array([11, 22, 33,  3])
print(a)            # array([11, 22, 33,  3])
print(b)            # array([11, 22, 33,  3])
print(c)            # array([11, 22, 33,  3])123456789101112131415161718192021
copy() 的赋值方式没有关联性
b = a.copy()    # deep copy
print(b)        # array([11, 22, 33,  3])
a[3] = 44
print(a)        # array([11, 22, 33, 44])
print(b)        # array([11, 22, 33,  3]) #b不会随着a的改变而改变
