# 第二节课

In [2]:
import PIL.Image as Image
import numpy as np

## 2.5 Numpy索引

### 一维索引

In [20]:
A = np.arange(3, 15)
print(A)
B = A.reshape(3, 4)
print(A.reshape(3, 4))
print(B[1])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 7  8  9 10]


### 二维索引

In [21]:
print(B[0][0])
print(B[0, 0])
print(B[2][:])
print(B[1:3, 2:])

for row in B:
    print(row)
for col in B.T:
    print(col)


3
3
[11 12 13 14]
[[ 9 10]
 [13 14]]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


### 迭代输出

In [23]:
print(B.flatten())
for item in B.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


# 2.6 Numpy array合并

## vstack 和 hstack

In [25]:
a = np.array([1, 1, 1])
b = np.array([2, 2, 2])
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]


## newaxis

In [33]:
c = np.array([1, 2, 3])
print(c[:, np.newaxis])
print(c[np.newaxis, :])

[[1]
 [2]
 [3]]
[[1 2 3]]


### np.concatenate()多个矩阵的合并

In [29]:
a = a.reshape((3, 1))
b = b.reshape((3, 1))
print(np.concatenate((a, b, b, a), axis = 0))
print(np.concatenate((a, b, b, a), axis = 1))

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


## 创建数组

In [6]:
my_array = np.array([1, 2, 3])
print(my_array, type(my_array), my_array.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)


In [9]:
my_array_2 = np.arange(1, 19, 2)
print(my_array_2)
print(type(my_array_2))
print(my_array_2.shape)
print(my_array_2.reshape(3, 3))

[ 1  3  5  7  9 11 13 15 17]
<class 'numpy.ndarray'>
(9,)
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [12]:
my_array_3 = np.linspace(1, 3, 10)
print(my_array_3)
# print(my_array_3.help)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


AttributeError: 'numpy.ndarray' object has no attribute 'help'

## array的属性和方法

In [15]:
arr = np.full((3, 7), 2)
print(arr)

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


In [16]:
print( 'The type is', type(arr) )
print( 'The dimension is', arr.ndim )
print( 'The length of array is', len(arr) )
print( 'The number of elements is', arr.size )
print( 'The shape of array is', arr.shape )
print( 'The stride of array is', arr.strides )
print( 'The type of elements is', arr.dtype )

The type is <class 'numpy.ndarray'>
The dimension is 2
The length of array is 3
The number of elements is 21
The shape of array is (3, 7)
The stride of array is (28, 4)
The type of elements is int32


In [ ]:
len()：数组长度为 2 (严格定义 len 是数组在「轴 0」的元素个数)
strides：跨度，(12，4)即在某一维度下为了获取到下一个元素需要「跨过」的字节数 (用元组来表示)，
int时4个字节数，float64 是 8 个字节数 (bytes)

## 数组的索引与切片

In [ ]:
# 概念
切片是获取一段特定位置的元素

索引是获取一个特定位置的元素

In [ ]:
# 区别
切片得到的是原数组的一个视图 (view) ，修改切片中的内容会改变原数组

索引得到的是原数组的一个复制 (copy)，修改索引中的内容不会改变原数组

切片得到原数组的视图 (view)，更改切片数据会更改原数组，而索引得到原数组的复制 (copy)， 更改索引数据不会更改原数组